function [HF, LF, Parms] = LoadVData()
%% LoadData.m
%  Loads AE data from a scan taken using BScan.m
%  Written by Alex Alvarez 12/08/18
%% TOC
%   @000 High Level Flags
%   @001 Load bScanParm
%   @002 Read HF data
%   @003 Read LF data
%% @000 High Level Flags
% High level flags to control functionality of script for easier user use
%% @001 Load bScanParm
% Read in .mat file generated by BScan.m to load bScanParm variables into
% the workspace
%  @001a Get filenames for use in later
[File, Path] = uigetfile(pwd,'*.mat'); % Have the user select the file 
cd(Path); % Change the working directory to the path
load([Path,File]); % Load bScanParm variables from the mat file into the workspace
% bScanParm is made up of the following quantities:
%   bScanParm.AxialFocus:       Axial Focus (double; in mm) 
%   bScanParm.LatFocus:         Lateral Focus (double; in mm)
%   bScanParm.ActiveScan:       If the VSX is in active scan mode (Boolean; =1)
%   bScanParm.Duration:         Duration of the scan (double; in ms)
%   bScanParm.AvgNum:           Number of averages at each scan position (double)
%   bScanParm.HFSamplingRate:   HF Sampling Rate (double; in MHz)
%   bScanParm.PulseRate:        Pulse Rate (double; in Hz) 
%   bScanParm.IsChirp:          If Chirp is Used (Boolean; =1)
%   bScanParm.ScriptRoot        Root name of the script (string)
%   bScanParm.nFrames           AMAQ: Is this PE or AE frames? 
%   bScanParm.numRep            AMAQ: Not actually sure what this is
%   bScanParm.PEMMode           If PEMMode is checked (Boolean; =1)
%   bScanParm.remote_path       Remote path used to save PE (string)
%   bScanParm.FileRoot          Name root for HF_avg, LF_avg, info files, etc. (string)
%   bScanParm.local_path        Local path that AE data was saved to (string)
%   bScanParm.wavlen            Wavelength of the transducer (double; in mm)
%   bScanParm.TransName         Name of the transducer (string)
%   bScanParm.TransFreq         Transducer Center Frequency (double; in MHz)
%   bScanParm.numFrames         AMAQ: What is this
%   bScanParm.ConfFile          The file used to create bScanParm (string)
%   bScanParm.script            The script root for the ConfFile (string)
%   bScanParm.Format            Structure that contains directories and files
%       bScanParm.Format.local                Path for the AE data (string)
%       bScanParm.Format.remote               Path for the PE data (string)
%       bScanParm.Format.date                 Date of scan (string) 
%       bScanParm.Format.filename             File Root name (no extension)(string)
%       bScanParm.Format.raw_pe               If Raw PE was saved (Boolean; =1)
%       bScanParm.Format.reconstructed_pe     If Reconstructed PE was saved (Boolean; =1)
%       bScanParm.Format.ae_dir               Directory for AE files (string)
%       bScanParm.Format.pe_dir               Directory for PE files (string)
%       bScanParm.Format.verasonics_IP        IP address for VSX (string)
%       bScanParm.Format.NI_IP                IP address for NI (string)
%       bScanParm.Format.filename2            File Root name (with scan parameters included)(string)
%       bScanParm.Format.Save_One             If Save One File Only was selected (Boolean; =1)
%       bScanParm.Format.Save_Avg             If Save Average was selected (Boolean; =1)
%       bScanParm.Format.PE_Pulse             AMAQ: Not sure what this is
%   bScanParm.Daq               Structure that contains DAQ info
%       bScanParm.Daq.HF              Structure that contains HF DAQ parameters
%           bScanParm.Daq.HF.PulseRate        Ultrasound pulse rate (double; in Hz)
%           bScanParm.Daq.HF.Rate_mhz         Sampling frequency (double; in MHz)
%           bScanParm.Daq.HF.Samples          Number of samples taken for a given imaging depth (double) 
%           bScanParm.Daq.HF.Gain             Digital gain on HF board (double)
%           bScanParm.Daq.HF.Range            Sampling range of HF board (double; in V)
%           bScanParm.Daq.HF.Channels         HF channels used (string)
%       bScanParm.Daq.LF              Structure that contains LF DAQ parameters used 
%           bScanParm.Daq.LF.Rate_hz          Sampling frequency (double; in kHz)
%           bScanParm.Daq.LF.Samples          Number of LF samples (based on slow time waveform) (double)
%           bScanParm.Daq.LF.Gain             Analog gain on the LF side (double)
%           bScanParm.Daq.LF.Range            Sampling range of LF board (double; in V)
%           bScanParm.Daq.LF.Channels         LF channels used (string)
%       bScanParm.Daq.PulseMode       If Pulse mode was used instead of burst mode (Boolean; =1)
%       bScanParm.Daq.UseNI           If NI should be used in the scan or just VSX is run (Boolean; =1)
%       bScanParm.Daq.STimeFilt       If slow time filter should be used in displaying the scan on NI GUI (Boolean; =1)
%       bScanParm.Daq.FilterDisplay   If fast time filter should be used in displaying the scan on NI GUI (Boolean; =1)
%   bScanParm.Scan              Structure that contains info on the scan  
%       bScanParm.Scan.Xpt            Number of x points in scan (double)
%       bScanParm.Scan.XDist          Range of x scan (double; in mm)
%       bScanParm.Scan.Ypt            Number of y points in scan (double)
%       bScanParm.Scan.YDist          Range of y scan (double; in mm)
%       bScanParm.Scan.SlowAxis       AMAQ: What is this and how is it used
%       bScanParm.Scan.FastAxis       AMAQ: What is this and how is it used
%       bScanParm.Scan.Duration_ms    Duration of the scan (double; in ms)
%       bScanParm.Scan.Sound_Speed    Speed of sound in the medium (double; in m/s)
%       bScanParm.Scan.Tpt            Number of time points collected (double)
%       bScanParm.Scan.steps          AMAQ: What is this and how is it used
%       bScanParm.Scan.Avg            Number of averages at each scan point (double)
%       bScanParm.Scan.Type           Type of scan (focused, plane, cone) (string)
%       bScanParm.Scan.ZDist          Range of z scan (double; in mm)
%       bScanParm.Scan.Zpt            Number of z points in scan (double)
%       bScanParm.Scan.pts            Total number of x,y,z,t points (double)
%       bScanParm.Scan.dtheta         AMAQ: Is this in radians or degrees dtheta step size for steering
%       bScanParm.Scan.ThetaRange     AMAQ: Is this in radians or degrees Range of angles 
%       bScanParm.Scan.PE_fps         Frames per second in the pulse echo movies (double)
%   bScanParm.Stim              Structure that contains info on the stimulation parameters      
%       bScanParm.Stim.IsChirp        If chirp was used in the scan (Boolean; =1) 
%       bScanParm.Stim.Amplitude      Amplitude of injected signal (double; V) 
%       bScanParm.Stim.Duration       AMAQ: What is this and how is it used
%       bScanParm.Stim.Waveform       Type of Waveform (Sin, Pls, ECG, etc.) (string) 
%       bScanParm.Stim.Width          Width of pulse (double; in ms) 
%       bScanParm.Stim.Cycles         Number of cycles in a burst (double) 
%       bScanParm.Stim.Frequency      Frequency of waveform (double; in Hz) 
%       bScanParm.Stim.Delay          Delay of pulse (double; in ms) 
%       bScanParm.Stim.Period         Period of pulse (double; in ms) 
%       bScanParm.Stim.IP             IP address of function generator (string) 
%       bScanParm.Stim.Ag             (1x2 Instrument Object Array)
%       bScanParm.Stim.tcp            (1x1 tcpip)
%       bScanParm.Stim.Phys_Trig      If physiologic triggering selected (Boolean; =1) 
%       bScanParm.Stim.Ext_Trig       If VSX expects trigger from the function generator (Boolean; =1) 
%   bScanParm.Velmex            Structure that contains info on the velmex/or any 2D scan      
%       bScanParm.Velmex.X            Defines which motor axis is X (double) 
%       bScanParm.Velmex.Y            Defines which motor axis is Y (double) 
%       bScanParm.Velmex.Speed        AMAQ: What are the units of speed used 
%       bScanParm.Velmex.Pause        AMAQ: What are the units of pause 
%       bScanParm.Velmex.Port         Defines the COM port used (double) 
%       bScanParm.Velmex.Axis         AMAQ: What is this and how is it used? 
%       bScanParm.Velmex.Motor        AMAQ: What is this and how is it used
%   bScanParm.nScanPt           Number of scan points (x*y) (double)
%   bScanParm.xlen              Range of x scan (double; in mm)
%   bScanParm.ylen              Range of y scan (double; in mm)
%   bScanParm.XSteps            Number of x steps in scan (double)
%   bScanParm.YSteps            Number of y steps in scan (double)
%   bScanParm.vsx_fs            AMAQ: What is this and how is it used?
%   bScanParm.daq               Structure that defines more daq parameters
%       bScanParm.daq.HFdaq           Structure that defines HF DAQ parameters 
%           bScanParm.daq.HFdaq.fs_MHz          Sampling frequency of HF board (double; in MHz)             
%           bScanParm.daq.HFdaq.pts             Number of HF sample (double)
%           bScanParm.daq.HFdaq.pulseRepRate_Hz Ultrasound pulse rate (double; in Hz) 
%           bScanParm.daq.HFdaq.NoBurstTriggers Number of triggers in a scan (double) 
%           bScanParm.daq.HFdaq.duration_ms     Duration of scan (double; in ms) 
%       bScanParm.daq.LFdaq           Structure that defines LF DAQ parameters 
%           bScanParm.daq.LFdaq.fs_Hz           Sampling frequency of LF board (double; in Hz) 
%           bScanParm.daq.LFdaq.pts             Number of LF samples (double) 
%   bScanParm.velmex            Structure that defines more velmex parameters 
%       bScanParm.velmex.XNStep                 Number of x points (double)
%       bScanParm.velmex.YNStep                 Number of y points (double)
%       bScanParm.velmex.XDist                  X range (double; in mm) 
%       bScanParm.velmex.YDist                  Y range (double; in mm)
%       bScanParm.velmex.SlowAxis               Slow Time Axis (string) 
%       bScanParm.velmex.FastAxis               Fast Time Axis (string)
Parms = bScanParm; % Output the variable Parm from the parameters in bScanParm
%% @002 Read HF Data
% Read high frequency voltage binary data collected on NI 5105 into the workspace
Xsteps = Parms.velmex.XNStep; % Define a temporary variable for the number of x points
Ysteps = Parms.velmex.YNStep; % Define a temporary variable for the number of y points
for XPt = 1:Xsteps
    for YPt = 1:Ysteps
        ScanPt = (YPt-1)*Xsteps+XPt; % Define the scan point. Add the current X point to the sum of the total number of y points completed (which is multiplied by the number of x points at each y point)
        hffile = strcat(Parms.Format.filename2,'_HF_Avg.dat'); % Define the name of the HF file
        if exist(hffile,'file') % If this file exists
            fid = fopen(hffile,'rb'); % Define the file id of the file and allow it to be readable as a non-text file
        else % If hffile does not exist
            hf_avg_file = regexprep(hffile,'_P[0-9]{4,4}_','_'); % Replace the non-averaged file name with a blank
            fid = fopen(hf_avg_file,'rb'); % Define the file id of this non-average file and allow it to be readable as a non-text file
        end

        if fid < 0 % If the file does not exist
            error('Cannot open HF data file'); % Output error message
        end

        n = fread(fid,1,'int32'); % Define the number of characters as the first integer value of the file
        sztype = fgets(fid,n); % Read in new line with the number of characters defined by n
        if(strcmpi(sztype(1:5),'ucsdi') == 0) % If this new line does not contain ucsdi
            fclose(fid); % Then close the file
            return; % And return to the workspace
        end
        
        Vers = fread(fid,1,'int32'); % Move the pointer past the date version value
        n = fread(fid,1,'int32'); % Determine the 3D size to read the array into 
        dsize = fread(fid,[1,n],'int32'); % Read in the dimensions of the array (Number of time points x Number of dimensions x Number of samples)
        
        blk_size = prod(dsize)*4; % AMAQ: Clearly the product of the dimensions by why multiplied by 4 What is the blk_size supposed to represent
        fseek(fid,blk_size*(ScanPt-1),'cof'); % Move the file marker in fid to blk_size * the ScanPt-1 starting from the current position in the file so as to read one block of data for each scan
        data = fread(fid,[blk_size/4,1],'single'); % Read in a vector reprsenting the total number of fast time samples * slow time points into data array with single precision
        tsize = dsize(1)*dsize(2)*dsize(3); % AMAQ: I know what dsize(3) represents as the number of burst triggers, but not sure of the others
        if tsize ~= length(data) % If tsize is not the same as the data just read in then a missing point exists at this scan point
            data = zeros(tsize,1); % Set all the data to zeros of the appropriate size at Missing Point
            disp(['Missing point ' num2str(ScanPt)]); % Report to the screen which scan point now has zeroes
        end
        data = reshape(data,fliplr(dsize)); % Reshape the data matrix to an 3-D array with fast time on the first dimension and slow time along the last dimension

        HF1{XPt,YPt} = permute(data,[1,3,2]); % Re-arrange data so that the 2nd and 3rd dimension are switched (i.e., the single unit is moved to the end)
        multiWaitbar(['Creating 4D Array y = ' num2str(YPt)],XPt/Xsteps); % Display progress bar
    
        Parms.dsize = dsize; % Define dsize in Parms structure
        Parms.ScanPt = ScanPt; % Define the scan point number in Parms structure
    end
end
HF = HF1;
% Define the output variable HF as the data just created
%% @003 Read LF Data
% Read low frequency voltage binary data collected on NI 6339 into the workspace
for XPt = 1:Xsteps
    for YPt = 1:Ysteps
        ScanPt = (YPt-1)*Xsteps+XPt; % Define the scan point. Add the current X point to the sum of the total number of y points completed (which is multiplied by the number of x points at each y point)
        lffile = strcat(Parms.Format.filename2,'_LF_Avg.dat'); % Define the low frequency average file
        fid = fopen(lffile); % Open the file ID for the file
        if fid < 0 % If an fid cannot be created
            error('Cannot open LF data file') % Report an error message to the screen
        end
        n = fread(fid,1,'int32'); % Read the number of characters to include in dsize
        sztype = fgets(fid,n); % Read in new line with the number of characters defined by n
        if(strcmpi(sztype(1:5),'ucsdi') == 0) % If this new line does not contain ucsdi
            fclose(fid); % Then close the file
            return; % And return to the workspace
        end
        Vers = fread(fid,1,'int32'); % Move the pointer past the date version value
        n = fread(fid,1,'int32'); % Read the number of characters to include in dsize
        dsize = fread(fid,[1,n],'int32'); % Define the size of the LF array based on the number of characters read
        blk_size = prod(dsize)*4; % AMAQ: Still don't know why this is multiplied by 4
        fseek(fid,blk_size*(ScanPt-1),'cof'); % Position the marker at the appropriate point for each scan point\
        data = fread(fid,fliplr(dsize),'single'); % Flip the orientation of the data matrix
        LF1{XPt,YPt} = data; % Define the LF1 matrix at each scan position as data

        Parms.nPts = dsize(2);
        Parms.numChan = dsize(1);
    end
end
LF = LF1;
